# Options
CC=c++
IPATH=/usr/include/gdal
LPATH=/usr/lib

CFLAGS=-Wall -O3 -frounding-math -fno-strict-aliasing -I$(IPATH) -L$(LPATH)

LDFLAGS=-g -O3  -D_REENTRANT -frounding-math -Wl,-Bsymbolic-functions -L$(LPATH) -lboost_thread-mt -lgmp -lgmpxx -lmpfr -lCGAL -lCGAL_Core -lgdal

all: prepair

prepair.o: prepair.cpp
	$(CC) $(CFLAGS) -c $^

prepair: prepair.o
	$(CC) $(LDFLAGS) $^ -o prepair

clean:
	rm -rf *.o prepair